# ===============================
# Netlify configuration file
# ===============================

[build]
  command = ""        # Pas de build (projet statique)
  publish = "docs"    # On déploie le dossier docs/

# (Optionnel) Redirection si un jour tu ajoutes un SPA
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
