name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Maven project
        run: mvn -B clean package -DskipTests

      - name: Run tests
        run: mvn -B test

      - name: Build Docker image
        run: docker build -t tp-cd-oumaima .
